### FileThread 2025.11.04

# REQ: SVGWrite https://github.com/mozman/svgwrite/

# call with 
#	python3 $binDir/findPath.py $reorder $threadMode $outputFile ${argv[@]} $pathsArray

# Takes as input a pathsArray of values n^2 long, which is an array of "distance" values between 
# each pair of nodes in a list of n nodes. In this case, it's generated by filethread.zsh
# by compressing each item individually and in pairs.

# TODO:
## file viewer: click a segment to open the two files at origin/destination offset


import os
import sys
import math
import numpy as np

import svgwrite
# from svgwrite import px


### arrays and variables
colors=['#1f77b4','#ff7f0e','#2ca02c','#d62728','#9467bd','#8c564b','#e377c2','#7f7f7f','#bcbd22','#17becf']

filesArray=[]
scoreMatrix=[]
pathsArray=[]
pathLengthArray=[]
matchesArray=[]
fullArray=[]

CSS_STYLES = """
	text {
		font-size: calc((100vh/1100) * 20);
		font-family: monospace, ui-monospace;
	}
	.metatext {
		opacity: 0;
		text-shadow: #ffffff calc(100vh/1100) calc(100vh/1100) calc((100vh/1100)*4);
	}
	g.segments:hover , g.segments:hover * {
		fill-opacity: 1;
		opacity: 1 !important;
		z-index: 9999 !important;
		display: block;
	}
	g.segments path {
		fill-opacity: 25%;	
		stroke-opacity: 25%;
		stroke-width: calc((100vh/1100) * 2);
	}	
	g.segments:hover path {
		fill-opacity: 1;
		opacity: 1 !important;
		stroke: #000000;
		stroke-opacity: 1;
	}
"""


#minRange = 8 # smallest matching region in bytes
#maxRange = 10240 # 10k ought to be enough for anyone
HSize = 1500
VSIZE = 1000 # 3:2 aspect ratio for the output image.
Padding = 50

reorder = sys.argv[1]
threadMode = sys.argv[2]
outputFile = sys.argv[3]
minRange = int(sys.argv[4])


# first n values after outputFile are the files, this is "matrixDimension"
matrixDimension = math.floor(math.sqrt(len(sys.argv[5:])))

filesArray = sys.argv[5:matrixDimension+5]

fullArray = [float(n) for n in sys.argv[matrixDimension+5:]]


### SETUP for drawing

# HScale = float(HSize /( matrixDimension - 1))
# d = draw.Drawing(HSize+Padding*2, VSIZE+Padding*2, origin=(-1*Padding,-1*Padding)) 

dwg = svgwrite.Drawing(filename=outputFile, debug=True)

dwg.defs.add(dwg.style(CSS_STYLES))

dwg.viewbox(minx=-1 * Padding, miny=-1 * Padding, width=HSize + 2*Padding, height=VSIZE+2*Padding)

### functions

def findBestPath( reorderMode ) :
	global STEP_LENGTHS
	global BEST_STEP_LENGTHS
	STEP_LENGTHS=[]
	global REORDERED_ARRAY
	global bestPath
	bestPath=[]

	if reorderMode=="skip":
		# skip the reordering and thread in the order files were given.
		REORDERED_ARRAY = filesArray
	else:
		# break the full array down into rows
		for rowNum in range(0, matrixDimension) :
			rowMatrix=[]
			for colNum in range(0, matrixDimension):
				matrixIndex=rowNum * matrixDimension + colNum
				rowMatrix.append(fullArray[matrixIndex])
		
			scoreMatrix.append(rowMatrix)
		
# 		print(scoreMatrix)
		# brute force finding nearest neighbors in each row
		for startNode in range(0, matrixDimension): # 0...4
		
# 			print(f"Checking start node {startNode}.")
		
			# checklist = 0 - len(scoreMatrix)
			nodeList = [x for x in range(0, matrixDimension)]
			# start with node 0
		#	startNode = 0
			pathLength = 0 
			currentNode = startNode
			currentPath = []
			STEP_LENGTHS.append([])

			# print(f"STARTNODE: {startNode}")	
			while len(nodeList) > 0:
# 				print(f" - to check: {len(nodeList)}")
				# print(f"Node: {currentNode}, List: {nodeList}")
			
				# remove that from the checklist
				if currentNode in nodeList:
					# print(f"REMOVING {currentNode}")
					nodeList.remove(currentNode)
					currentPath.append(currentNode)
					# print(currentPath)
				else:
					break

### how are scores above 1?				
				minScore=float(2.0)
		
				for candidate in nodeList:
		
					if scoreMatrix[currentNode][candidate] < minScore:
						minScore = scoreMatrix[currentNode][candidate]
						nextNode = candidate
		
				# running tally of path length
				pathLength += minScore
				
				STEP_LENGTHS[startNode].append(minScore)
				# add the step to the array recording step lengths
# 				print(f"{currentNode} -> {nextNode} = {minScore}")
				currentNode = nextNode
		
			# print(currentPath)
			pathsArray.append(currentPath)
			pathLengthArray.append(pathLength)
		
# 		print(f"Possible paths: {len(pathLengthArray)}")
		
		# find shortest complete path length 
		shortestPath=pathLengthArray.index(min(pathLengthArray))
	
		bestPath=pathsArray[shortestPath]
	
		if reorderMode=="reverse":
			bestPath.reverse()
		
		BEST_STEP_LENGTHS=STEP_LENGTHS[shortestPath]
	
		if reorderMode=="reverse":
			BEST_STEP_LENGTHS.reverse()
			BEST_STEP_LENGTHS.pop(0) # remove the stub length 2.0
		else:
			BEST_STEP_LENGTHS.pop(-1) # remove the stub length 2.0

		# print(bestPath)
		# print(BEST_STEP_LENGTHS)
	
		REORDERED_ARRAY = [ filesArray[x] for x in bestPath ]
	
		# print(REORDERED_ARRAY)


def update_progress(caption,progress,total):
	sys.stdout.write(f'\r{caption}: [{progress}/{total}]')
# 	sys.stdout.flush()


### RESET
def reset():
	matchesArray=[]
	threadArray=[]
	
	global FILES_BYTES_ARRAY
	FILES_BYTES_ARRAY=[]

	global VScale
	VScale = 1

	### Convert binary data to hex
	for fileNum in range(0,len(REORDERED_ARRAY)):

		FILE_TO_READ=open(REORDERED_ARRAY[fileNum],"rb").read()	

		FILE_BYTES=FILE_TO_READ[0:]
### replace strings of zeroes? Or maybe just at the end?
### this handles "sparse" files
		sparseLength=1
		while FILE_BYTES[-1 * sparseLength] == 0:
			sparseLength += 1 

# 		print(sparseLength)
# 		print(FILE_BYTES[-1 * sparseLength])
#		FILES_BYTES_ARRAY.append(FILE_TO_READ[0:].replace(b'\x00\x00',b''))
		FILES_BYTES_ARRAY.append(FILE_BYTES[0:-1 * sparseLength])
			
		pVScale = VSIZE/len(FILES_BYTES_ARRAY[fileNum])	# fit the largest file vertically, but scale all files the same amount. 

# Can't do this with original binary size since some are 00 padded or "sparse"
		if pVScale < VScale:
			VScale = pVScale
			

# for each pair of files, find matching segments.

def matchBlocks(  ):	

	for originFile in range(0, len(FILES_BYTES_ARRAY)-1):
# 		print(f" Completed {originFile} of {len(FILES_BYTES_ARRAY)}") 
		targetFile = originFile+1
		matchCount=0
		matchSum=0
		diffSum=0
		
		lastResult=""
		originByte=0
		
		originLength = len(FILES_BYTES_ARRAY[originFile]) - 1
		maxRange = originLength
		
# 		print(f" {targetFile}/{len(FILES_BYTES_ARRAY)}")
		while originByte < originLength :
	
			update_progress(f"Matching {originFile}-{targetFile}", originByte, originLength)
	
			for byteLength in range(minRange,originLength - originByte):
		
				if int(originByte + byteLength) < int(originLength) : # don't try to read past the end. oof.
				
					charLength = int(byteLength)
					originChars = int(originByte)
							
					byteBlock = FILES_BYTES_ARRAY[originFile][originChars:originChars+charLength] # block of bytes to search for

				# do the actual search	- just for the first instance
					wordIndex = FILES_BYTES_ARRAY[targetFile].find(byteBlock)
							
					if wordIndex != -1:
						byteIndex = int(wordIndex)		
						lastResult= f"{originFile}:{targetFile}\t{byteLength}\t{originByte}\t{byteIndex}"
						
					else:
								
						if len(lastResult) > 0: #success!

							currentMatch=[]
							currentMatch.append(byteLength-1)

							for i in range(0,originFile):
								currentMatch.append(None)

							currentMatch.append(originByte)

							for i in range(0, (targetFile - originFile) - 1):
								currentMatch.append(None)
							
							currentMatch.append(byteIndex)

							for i in range(targetFile, len(FILES_BYTES_ARRAY)-1):
								currentMatch.append(None)
							
#								print(currentMatch)

							matchesArray.append(currentMatch)

							indexDiff=abs(byteIndex - originByte)
							if indexDiff > byteLength:
								indexDiff = byteLength/2
							elif indexDiff == 0:
								indexDiff = byteLength * 2
							else:
								indexDiff = byteLength
							
							matchCount+=1
							matchSum+=indexDiff
							lastResult="" # reset for next go-round
						break
				else: 
					break
				
				
			if len(lastResult) > 0:	### matched on end of file/bytesize loop
				
				byteIndex = int(wordIndex)

				currentMatch=[]
				currentMatch.append(byteLength-1)

				for i in range(0,originFile):
					currentMatch.append(None)

				currentMatch.append(originByte)

				for i in range(0, (targetFile - originFile) - 1):
					currentMatch.append(None)
				
				currentMatch.append(byteIndex)

				for i in range(targetFile, len(FILES_BYTES_ARRAY)-1):
					currentMatch.append(None)

#					print(currentMatch)
				matchesArray.append(currentMatch)
				
				
				indexDiff=abs(byteIndex - originByte)
				if indexDiff > byteLength:
					indexDiff = byteLength/2
				elif indexDiff == 0:
					indexDiff = byteLength * 2
				else:
					indexDiff = byteLength
				
				matchCount+=1
				matchSum+=indexDiff
				
				lastResult="" # reset for next go-round
				
# 			originByte = originByte+(byteLength-2) # skip ahead past matched area, but overlap last 2 bytes 
			originByte = originByte+int(byteLength-(minRange/2))
		
# for each match found from file n to n+1, look for it in files n+2...
# blocklength, file0loc, file1loc, ...filenloc

def doThreads(  ):
# 	progress=0

	for blockMatch in matchesArray:
# 		progress+=1
# 		update_progress(progress, len(matchesArray))

# find first entry X with a value.
		for x in range(1,len(blockMatch)):
# originFile = X-1
			if blockMatch[x] is None:
				continue
			else:
				originChars=int(blockMatch[x])
				originFile=x-1
				charLength=blockMatch[0]
				byteBlock = FILES_BYTES_ARRAY[originFile][originChars:originChars + charLength] # block of bytes to search for
				break

			
			
def drawThreads() :
	global STEP_LENGTHS
	global HScale
	sys.stdout.write("\rGenerating graph.")
		
	RectX=[]
	colorIndex=0	# for rotating through color palette
	# draw translucent arc between right side of origin and left side of destination
	progress=0
	
### draw file bars
### adjust spacing, save in array
	rectSum = 0
	RectX.append(rectSum) # start at X=0
	
	for fileNum in range(1,len(REORDERED_ARRAY)):
		if reorder == "skip":
# 			HScale = float(HSize / (min(pathLengthArray) - 1))
			HScale = float(HSize /( matrixDimension - 1))
			rectSum = HScale * fileNum

		else:
		# scale graph to match relative distances between items?
			totalPath = float(sum(BEST_STEP_LENGTHS))
			HScale = float(HSize/totalPath)

			if fileNum == len(REORDERED_ARRAY):
				rectSum = HSize - 10
			else:
				### get total path length, step_length/total * HSize
				rectSum += float(BEST_STEP_LENGTHS[fileNum-1] * HScale)

		RectX.append(rectSum)	

	# print(RectX)

### draw file bars and attach segments
# 	print(RectX)		

	for fileNum in range(0,len(REORDERED_ARRAY)):
		
# 		emptyRect = dwg.rect(insert=(RectX[fileNum] , 0), size=(10, VSIZE), fill="#CCCCCC", stroke='#000000', stroke_width=1)
		emptyRect = dwg.rect(insert=(RectX[fileNum] , 0), size=(10, len(FILES_BYTES_ARRAY[fileNum]) * VScale), fill="#CCCCCC", stroke='#000000', stroke_width=1)

		

		dwg.add(emptyRect)
	
### Draw text labels
		rectLabelLine = dwg.path(d=f"M {RectX[fileNum]-4},{VSIZE} " + f"L {RectX[fileNum]-4},{0}")

		rectLabel = svgwrite.text.Text("")
		rectLabel.add(svgwrite.text.TextPath(rectLabelLine, text=os.path.basename(REORDERED_ARRAY[fileNum]), startOffset=20))
	
		dwg.add(rectLabelLine)
		dwg.add(rectLabel)
		
### draw segment rectangles on file bars	
	for matchArray in matchesArray:
		progress+=1
		update_progress("Drawing", progress, len(matchesArray))
		fillColor=colors[colorIndex]

# byte length
		boxHeight=matchArray[0]*VScale
# 		print(f"Length: {matchArray[0]}")	

### each matchArray = 1 segment. Find where it starts.
		for fileNum in range(1,len(matchArray)-1):
# 			print(f"FileNum: {fileNum}")
# 			print(matchArray[fileNum])			
	
			if (matchArray[fileNum] != None ) and (matchArray[fileNum+1] != None ):
	
				segment = dwg.add(dwg.g(class_="segments"))
	
				CoordY = int(matchArray[fileNum]) * VScale
				
# 				segment.add(dwg.rect(insert=(RectX[fileNum-1], CoordY), size=(10, boxHeight), fill=fillColor, fill_opacity=.5))
	
	### draw thread for each segment	
				CoordY2 = matchArray[fileNum+1]* VScale
					
				p = dwg.path(d=f"M {RectX[fileNum - 1]},{CoordY}"+f"L{RectX[fileNum-1]+10},{CoordY}"+f"Q{RectX[fileNum]},{(CoordY + CoordY2)/2},{RectX[fileNum]}, {CoordY2} L{RectX[fileNum]}, {boxHeight + CoordY2}"+f"Q {RectX[fileNum]}, { (CoordY + CoordY2)/2 + boxHeight}, {RectX[fileNum - 1]+10},{CoordY + boxHeight}"+f"L{RectX[fileNum-1]},{CoordY + boxHeight}" + "Z", fill=fillColor, stroke=fillColor)
				segment.add(dwg.g(class_="threads")).add(p)
	
	# add a text block for each thread with byte offset at origin, destination, and length.
				if threadMode=="txt" :
					originTXT = matchArray[fileNum]
					destinationTXT = matchArray[fileNum+1]
					lengthTXT = f'{matchArray[0]} characters'
				else:
					originTXT = f'0x{matchArray[fileNum]:X}'
					destinationTXT = f'0x{matchArray[fileNum+1]:X}'
					lengthTXT = f'0x{matchArray[0]:X} bytes'
				
	
	# add as class "metadata" child of p, fill_opacity 0 				
				metadata = segment.add(dwg.g(class_="metatext")).add(dwg.text("", x=[f'{RectX[fileNum - 1] + 14}'], y=[f'{int(CoordY)+4}']))
				metadata.add(dwg.tspan(f"Origin:  {originTXT}", dy=['1.1em'], x=[f'{RectX[fileNum - 1] + 14}']))
				metadata.add(dwg.tspan(f"Destination:  {destinationTXT}", dy=['1.1em'], x=[f'{RectX[fileNum - 1] + 14}']))
				metadata.add(dwg.tspan(f"Length: {lengthTXT}", dy=['1.1em'], x=[f'{RectX[fileNum - 1] + 14}']))
	
		# next color in rotation					
				colorIndex+=1
				if colorIndex == len(colors):
					colorIndex=0

	# save the SVG
	dwg.save()



### Do the needful
findBestPath( reorder )
reset()
matchBlocks()
doThreads()
drawThreads()